# -*- coding: utf-8 -*-
"""Copy of python2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15m-4t-65I6qhrT0dr3KWRx0nRPZlqRdD
"""

name= "harshit"
print(name[0:2])

name="I love to read books"
print(name[5:8])

name="I love to read books"
print(name[0:5])

name="I love to read books"
print(name[::-1])

name= "akshansh"
print("akshnash"*5)

name="akshansh"
title="dubey"
print("akshansh"*5)
print(name+" "+title)

name= "akshansh"
title= "dubey"
print("akshansh"*5)
print(name+"_"+title)
print("hit"in name)

name= "akshansh"
title= "dubey"
print("deepak"*5)
print(name+" "+title)
print(name.upper())
print(name.lower())
print(name.title())
print(name.count("a"))
print(name.find("a"))
print(name.capitalize())

name= "akshansh"
title= "dubey"
print("akshansh"*5)
print(name+" "+title)
print(name.upper())
print(name.lower())
print(name.title())
print(name.count("a"))
print(name.find("a"))
print(name.replace("akshansh","dubey"))

name= "akshansh"
print(name.split())
print(len(name))

a= [10,20,20]
b= [20,30]
print(a+b)

a= [10,20,20]
b= [20,30]
print(a+b)
print(a[2])

name= "akshansh"
print(name.count(""))

a=[10,15,30,220,55,500]
b=[24,35,45,56,77]
print(a+b)
print(a.extend(b))
print(a)
print([10,15]*3)

a=[10,15,30,220,55,500]
a.sort()
print(a)
a.reverse()
print(a)
print(a.index(30))
print(a.count(220))

a= [10,15,30,220,55,500]
print(a.clear())
print(a)

pip install notebook

import pandas as pd
marks = pd.Series([85,90,78,95])
print(marks)

df = pd.read_csv('/content/Zomato-data-.csv')
print(df)

df

df.head(15)

df.tail()

df.info

df.columns

df.dtypes

df["future_age"] = df["Age"] + 5
df.rename(columns={"Name": "student_Name"}, inplace=True)
df.drop("Age", axis=1, inplace=True)
print(df)



import pandas as pd
student= {
    "Name":["Rahul","Amit","Priya"],
    "Age":[20,21,19],
    "Marks":[80,90,95]
}
df= pd.DataFrame(student)
print(df)

import pandas as pd

data = {
    "Emp_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja"],
    "Age": [24,25,23,28,30,26,27,24,29,25],
    "Department": ["HR","IT","Sales","IT","HR",
                   "Finance","Sales","IT","Finance","HR"],
    "Salary": [35000,50000,45000,60000,38000,
               55000,47000,62000,58000,40000],
    "City": ["Delhi","Lucknow","Noida","Delhi","Jaipur",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

df.sample()

df.describe()

df.shape

df.dtypes

df.info

df.columns

df.head()

df.tail()

df[["Name", "Salary"]]

df[df["Salary"]>5000]

df[df["Department"] == "IT"]

df.sort_values(by="Salary")

df.sort_values("Salary", ascending=False)

df["Salary"].max()

df["Salary"].min()