# -*- coding: utf-8 -*-
"""python2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzGaTL3bavfmGN56K4a49Zfwb8xTCT1D
"""

name= "harshit"
print(name[0:2])

name="I love to read books"
print(name[5:8])

name="I love to read books"
print(name[0:5])

name="I love to read books"
print(name[::-1])

name= "akshansh"
print("akshnash"*5)

name="akshansh"
title="dubey"
print("akshansh"*5)
print(name+" "+title)

name= "akshansh"
title= "dubey"
print("akshansh"*5)
print(name+"_"+title)
print("hit"in name)

name= "akshansh"
title= "dubey"
print("deepak"*5)
print(name+" "+title)
print(name.upper())
print(name.lower())
print(name.title())
print(name.count("a"))
print(name.find("a"))
print(name.capitalize())

name= "akshansh"
title= "dubey"
print("akshansh"*5)
print(name+" "+title)
print(name.upper())
print(name.lower())
print(name.title())
print(name.count("a"))
print(name.find("a"))
print(name.replace("akshansh","dubey"))

name= "akshansh"
print(name.split())
print(len(name))

a= [10,20,20]
b= [20,30]
print(a+b)

a= [10,20,20]
b= [20,30]
print(a+b)
print(a[2])

name= "akshansh"
print(name.count(""))

a=[10,15,30,220,55,500]
b=[24,35,45,56,77]
print(a+b)
print(a.extend(b))
print(a)
print([10,15]*3)

a=[10,15,30,220,55,500]
a.sort()
print(a)
a.reverse()
print(a)
print(a.index(30))
print(a.count(220))

a= [10,15,30,220,55,500]
print(a.clear())
print(a)

